# Generated by Django 4.1 on 2023-10-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('imagge', models.ImageField(blank=True, upload_to='')),
                ('texto', models.TextField(blank=True)),
            ],
        ),
    ]
