# Generated by Django 4.1 on 2023-10-23 17:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aviso',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aviso',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
