# Generated by Django 4.1 on 2023-10-23 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0002_aviso_created_date_aviso_modified_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aviso',
            old_name='imagge',
            new_name='imagem',
        ),
    ]
