# Generated by Django 4.1 on 2023-10-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0004_alter_aviso_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aviso',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
