# Generated by Django 4.1 on 2023-11-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0007_alter_aviso_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aviso',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
